# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
#pip install gmaps

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [3]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../weather_data/WeatherPy_database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df =pd.read_csv( "../weather_data/WeatherPy_database.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Puerto Ayora,EC,2022-10-30 22:02:19,-0.7393,-90.3518,65.55,98,98,5.99,light rain
1,1,Shuangcheng,CN,2022-10-30 22:02:20,45.3500,126.2833,44.98,86,100,14.83,overcast clouds
2,2,Port Elizabeth,ZA,2022-10-30 22:02:20,-33.9180,25.5701,61.11,92,96,7.00,overcast clouds
3,3,Port Alfred,ZA,2022-10-30 22:02:20,-33.5906,26.8910,59.18,96,99,4.00,overcast clouds
4,4,Hermanus,ZA,2022-10-30 22:02:20,-34.4187,19.2345,57.79,55,100,13.62,overcast clouds

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [4]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip?  77
What is the maximum temperature you would like for your trip?  99

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [5]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
# Display sample data
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
5,5,Hobyo,SO,2022-10-30 22:02:21,5.3505,48.5268,79.23,74,15,8.39,few clouds
20,20,Faanui,PF,2022-10-30 22:02:25,-16.4833,-151.7500,80.24,72,29,13.82,scattered clouds
23,23,Cockburn Town,TC,2022-10-30 22:01:20,21.4612,-71.1419,82.31,76,2,17.34,clear sky
24,24,Port Hueneme,US,2022-10-30 22:02:27,34.1478,-119.1951,89.51,51,0,9.22,clear sky
27,27,Sola,VU,2022-10-30 22:02:28,-13.8833,167.5500,81.43,67,3,3.76,clear sky
31,31,Atuona,PF,2022-10-30 22:02:29,-9.8000,-139.0333,77.36,74,6,17.27,clear sky
33,33,Vaitape,PF,2022-10-30 22:02:30,-16.5167,-151.7500,80.28,72,31,13.82,scattered clouds
38,38,Butaritari,KI,2022-10-30 22:02:31,3.0707,172.7902,79.25,70,77,7.76,broken clouds
41,41,Mongo,TD,2022-10-30 22:02:32,12.1844,18.6930,83.68,26,48,6.08,scattered clouds
43,43,Umm Kaddadah,SD,2022-10-30 22:02:33,13.6017,26.6876,80.92,24,71,14.90,broken clouds

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [6]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_df =  preferred_cities_df.copy()
clean_df.dropna(how='any', inplace=True)
clean_df

# Display sample data

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
5,5,Hobyo,SO,2022-10-30 22:02:21,5.3505,48.5268,79.23,74,15,8.39,few clouds
20,20,Faanui,PF,2022-10-30 22:02:25,-16.4833,-151.7500,80.24,72,29,13.82,scattered clouds
23,23,Cockburn Town,TC,2022-10-30 22:01:20,21.4612,-71.1419,82.31,76,2,17.34,clear sky
24,24,Port Hueneme,US,2022-10-30 22:02:27,34.1478,-119.1951,89.51,51,0,9.22,clear sky
27,27,Sola,VU,2022-10-30 22:02:28,-13.8833,167.5500,81.43,67,3,3.76,clear sky
...,...,...,...,...,...,...,...,...,...,...,...
661,661,Yaan,NG,2022-10-30 22:19:51,7.3833,8.5667,78.28,45,84,0.76,broken clouds
668,668,Mayor Pablo Lagerenza,PY,2022-10-30 22:19:53,-19.9309,-60.7718,98.26,29,3,14.79,clear sky
669,669,Manoel Urbano,BR,2022-10-30 22:19:54,-8.8389,-69.2597,85.21,60,92,3.09,overcast clouds
670,670,America Dourada,BR,2022-10-30 22:19:54,-11.4553,-41.4361,81.37,44,69,10.83,broken clouds
673,673,Kokopo,PG,2022-10-30 22:19:55,-4.3520,152.2633,83.32,70,70,3.15,light rain

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [7]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = clean_df[["City","Country","Max Temp","Current Description","Lat","Lng"]].copy()

# Display sample data
hotel_df["Hotel Name"] = " "
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Hobyo,SO,79.23,few clouds,5.3505,48.5268,
20,Faanui,PF,80.24,scattered clouds,-16.4833,-151.7500,
23,Cockburn Town,TC,82.31,clear sky,21.4612,-71.1419,
24,Port Hueneme,US,89.51,clear sky,34.1478,-119.1951,
27,Sola,VU,81.43,clear sky,-13.8833,167.5500,
31,Atuona,PF,77.36,clear sky,-9.8000,-139.0333,
33,Vaitape,PF,80.28,scattered clouds,-16.5167,-151.7500,
38,Butaritari,KI,79.25,broken clouds,3.0707,172.7902,
41,Mongo,TD,83.68,scattered clouds,12.1844,18.6930,
43,Umm Kaddadah,SD,80.92,broken clouds,13.6017,26.6876,

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [8]:
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]
    
    # 6c. Get latitude and longitude from DataFrame.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
hotels

{'error_message': 'The provided API key is invalid.',
 'html_attributions': [],
 'results': [],
 'status': 'REQUEST_DENIED'}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [10]:
# # Review the parameters to search for a hotel
# params = {
#     "radius": 5000,
#     "type": "lodging",
#     "key": g_key
# }        

# # Iterate through the DataFrame.
# for index, row in hotel_df.iterrows():
    
#     # Get the latitude and longitude.
#     lat = row["Lat"]
#     lng = row["Lng"]

#     # Add the latitude and longitude to location key for the params dictionary.
#     params["location"] = f"{lat},{lng}"

#     # Use the search term: "lodging" and our latitude and longitude.
#     base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
#     # Make request and get the JSON data from the search.
#     hotels = requests.get(base_url, params=params).json()
    
#     # Grab the first hotel from the results and store the name.
#     try:
#         hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
#     except (IndexError):
#         print("Hotel not found....skipping.")

In [11]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
base_url

'https://maps.googleapis.com/maps/api/place/nearbysearch/json'

In [12]:
# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Hobyo,SO,79.23,few clouds,5.3505,48.5268,
20,Faanui,PF,80.24,scattered clouds,-16.4833,-151.7500,
23,Cockburn Town,TC,82.31,clear sky,21.4612,-71.1419,
24,Port Hueneme,US,89.51,clear sky,34.1478,-119.1951,
27,Sola,VU,81.43,clear sky,-13.8833,167.5500,
31,Atuona,PF,77.36,clear sky,-9.8000,-139.0333,
33,Vaitape,PF,80.28,scattered clouds,-16.5167,-151.7500,
38,Butaritari,KI,79.25,broken clouds,3.0707,172.7902,
41,Mongo,TD,83.68,scattered clouds,12.1844,18.6930,
43,Umm Kaddadah,SD,80.92,broken clouds,13.6017,26.6876,

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [13]:
# Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(how='any')

# Display sample data
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Hobyo,SO,79.23,few clouds,5.3505,48.5268,
20,Faanui,PF,80.24,scattered clouds,-16.4833,-151.7500,
23,Cockburn Town,TC,82.31,clear sky,21.4612,-71.1419,
24,Port Hueneme,US,89.51,clear sky,34.1478,-119.1951,
27,Sola,VU,81.43,clear sky,-13.8833,167.5500,
...,...,...,...,...,...,...,...
661,Yaan,NG,78.28,broken clouds,7.3833,8.5667,
668,Mayor Pablo Lagerenza,PY,98.26,clear sky,-19.9309,-60.7718,
669,Manoel Urbano,BR,85.21,overcast clouds,-8.8389,-69.2597,
670,America Dourada,BR,81.37,broken clouds,-11.4553,-41.4361,
673,Kokopo,PG,83.32,light rain,-4.3520,152.2633,

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [14]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [20]:
# Set the file name.
output_data_file = "../weather_data/weatherPy_vacation.csv"

# Create a CSV file by using the clean_hotel_df DataFrame
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [ ]:
# Review the formatting template provided
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [ ]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# Display sample data
hotel_info[:10]

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [ ]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [ ]:
# Add a marker layer for each city to the map. 
# YOUR CODE HERE

# Create a figure to add the Google map as a layer
# YOUR CODE HERE

# Display the figure containing the map
# YOUR CODE HERE